version: '3.4'
services:
  anime-webapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    restart: always
    networks:
      - my-network

  db:
    image: mcr.microsoft.com/mssql/server
    restart: always
    environment:
      SA_PASSWORD: mysecretpassword
      ACCEPT_EULA: Y
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
